# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy-app = "tcp://127.0.0.1:26658"
moniker = "my-local-testnet"
mode = "validator"
fast_sync = false
db-backend = "goleveldb"
db-dir = "data"
log-level = "info"
log-format = "plain"

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]
cors_allowed_methods = ["HEAD", "GET", "POST"]
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time"]

[p2p]
laddr = "tcp://0.0.0.0:26656"
external_address = ""
seeds = ""
persistent_peers = ""
upnp = false
addr_book_strict = false
max_num_inbound_peers = 0
max_num_outbound_peers = 0
unconditional_peer_ids = ""
persistent_peers_max_dial_period = "0s"
flush_throttle_timeout = "10ms"
max_packet_msg_payload_size = 1024
send_rate = 20480000
recv_rate = 20480000
pex = false
seed_mode = false
private_peer_ids = ""

[mempool]
size = 10000
cache_size = 20000
max_txs_bytes = 1073741824
max_tx_bytes = 1048576
max_gas_wanted_per_tx = "50000000"
max_gas_used_per_block = "100000000"

[consensus]
wal_file = "data/cs.wal/wal"
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1s"
double_sign_check_height = 0
skip_timeout_commit = false
create_empty_blocks = true
create_empty_blocks_interval = "0s"
peer_gossip_sleep_duration = "10ms"
peer_query_maj23_sleep_duration = "2s"

[tx_index]
indexer = "kv"
