[state-commit]
sc-enable = true
sc-zero-copy = false
sc-async-commit-buffer = 100
sc-keep-recent = 1
sc-snapshot-interval = 10000
sc-snapshot-writer-limit = 2
sc-cache-size = 100000

[state-store]
ss-enable = true
ss-backend = "pebbledb"
ss-async-write-buffer = 100
ss-keep-recent = 100000
ss-prune-interval = 600
ss-import-num-workers = 1

[evm]
http_enabled = true
http_port = 8545
ws_enabled = true
ws_port = 8546
read_timeout = "30s"
read_header_timeout = "10s"
write_timeout = "30s"
idle_timeout = "120s"
simulation_gas_limit = 10000000
simulation_evm_timeout = "60s"
cors_origins = "*"
ws_origins = "*"
filter_timeout = "120s"
checktx_timeout = "5s"
max_tx_pool_txs = 1000
slow = false
deny_list = []
max_log_no_block = 10000
max_blocks_for_log = 2000
max_subscriptions_new_head = 10000
enable_test_api = false

[evm-log]
level = "debug"
module = ["eth", "evm", "vm", "state", "txpool", "rpc", "api", "ethapi", "ethclient", "ethfilter", "ethstats", "ethsync", "ethdb", "ethmisc", "ethminer", "ethnet", "ethprotocol", "ethserver", "ethservice", "ethtest", "ethtx", "ethutil", "ethvm", "ethweb3", "ethworker"]
file = "stdout"